### ISSUE TITLE
Server crashes when client attempts to read frames (standalone only)

### ISSUE THREAD

**Issue by rsouthgate** [keijiro/Funnel#14]
I've seen #7 and #8 and have a similar issue... though there is definitely a syphon server running when I run the standalone build of my app.

However as soon as a client attempts to connect to it (tried both madmapper and the simple syphon client from syphon example) the unity app will crash. Yet when running through the unity editor everything runs ok.

I've attached the player log so you can see the crash - it means nothing to me!

[Player.log](https://github.com/keijiro/Funnel/files/1517100/Player.log)

**Comment by keijiro** [comment]
I'm going to discontinue this plugin (Funnel) because I started working on the new plugin (KlakSyphon).

https://github.com/keijiro/KlakSyphon

Please consider migrating to the new plugin to get better stability and future support.

I'm closing this issue. Please feel free to reopen for further questions.
