### ISSUE TITLE
Add Syphon client functionality

### ISSUE THREAD

**Issue by keijiro** [keijiro/Funnel#6]
It should be capable of receiving Syphon frames into a render texture.

**Comment by jonasfehr** [comment]
hi keijiro
great work... Super plugin and with your [sendRenderTexture](https://gist.github.com/keijiro/50fd48d6dd24c915d1bd4ce7ad62cd30) script even better.
However, I am now conflicting with funnel and the standard unity syphon plugin, as they don't work together at the same time...
A client funtctionality woul be absolutely great, as I prefer to work with the newer implementations, respektively don't like to downgrade the GL version in order to run my app.
Best
Jonas

P.S.: here my use so far, projection mapping setup with perspective correction for a camera. The samm screen shows the camera...

![img_1270](https://cloud.githubusercontent.com/assets/6086501/17025474/50efb09e-4f5c-11e6-919f-f67fc4716e3f.JPG)

**Comment by dpentecost** [comment]
Great to see that you " self-assigned this 17 days ago" - A Funnel client would reboot Unity Syphon work. What can I do to help make this happen? Send you snacks? Donate to you through PayPal? ;)

**Comment by EricMotion** [comment]
Any update on this? I'm using unity 5.4 beta, and syphons plugins don't seem to want to shake hands w/ the newer version... Funnel client would be !!!!!

**Comment by keijiro** [comment]
Sorry now I'm super busy and have no time for this. This one would take a lot of time (mainly for QA). I have to carve out time for it...

**Comment by PabloMontero** [comment]
Funnel client +1

**Comment by gfngr** [comment]
Funnel client would be super awesome!

**Comment by grigM** [comment]
Hello @keijiro !!
First of all, i wan't to thank you for great work with Funnel and other amazing Unity tools! 
And second, i wan't to ask..  Is there any chance to see Funnel Client functionality in future ? 
I can help with any testing or documentation, or even money, If you need!  
I'm sure that many people can make donation for this.

**Comment by keijiro** [comment]
The new Syphon plugin supports client functionality.

https://github.com/keijiro/KlakSyphon

I'm going to discontinue working on this plugin (Funnel). Please consider migrating to the new plugin for future support.

I'm closing this issue. Please feel free to reopen for further questions.
